version: "3"

volumes:
  nodejs_node_modules:
    driver: local

services:
  nodejs:
    build:
      context: "./"
      dockerfile: "docker/nodejs/Dockerfile"
      args:
        - CURRENT_UID=${CURRENT_UID}
    tty: true
    volumes:
      - ./:/app
      - nodejs_node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: bash /app/docker/nodejs/start_dev_server.sh
    working_dir: /app
    user: $CURRENT_UID
    environment:
      - CURRENT_UID
      - MANUAL
      - WEBTEST
      - WEBPACK_DEV_SERVER_HOST=0.0.0.0
      - WEBPACK_DEV_SERVER_PORT=8080

