version: "3"

volumes:
  nodejs_node_modules:
    driver: local

services:
  nodejs:
    build:
      context: "./"
      dockerfile: "docker/nodejs/Dockerfile"
    tty: true
    volumes:
      - ./:/home/node/app
      - nodejs_node_modules:/home/node/app/node_modules
    ports:
      - "8080:8080"
    command: bash /home/node/app/docker/nodejs/start_dev_server.sh
    working_dir: /home/node/app
    user: ${CURRENT_UID}
    environment:
      - CURRENT_UID
      - MANUAL
      - WEBTEST
      - WEBPACK_DEV_SERVER_HOST=0.0.0.0
      - WEBPACK_DEV_SERVER_PORT=8080
