version: "3"
services:
  nodejs:
    build:
      context: "./"
      dockerfile: "docker/nodejs/Dockerfile"
    tty: true
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: bash /home/node/app/scripts/start_dev_server.sh
    working_dir: /home/node/app
    environment:
      - WEBPACK_DEV_SERVER_HOST=0.0.0.0
      - WEBPACK_DEV_SERVER_PORT=8080

